### ISSUE TITLE
3.4 devices can be switched off but can not be switched back on

### ISSUE THREAD

**Issue by Monacoslo** [willemwouters/localtuya_synced#2]
## Environment

- Localtuya version: latest
- Last working localtuya version (if known and relevant): 
- Home Assistant Core version: latest
- [] Are you using the Home Assistant Tuya Cloud component ? no
- [x] Are you using the Tuya App in parallel ? 

## Steps to reproduce
The integration was included using those steps:
git clone --recursive https://github.com/willemwouters/localtuya_synced.git
copy localtuya_synced/custom_components/localtuya into your HA instance custom_components/localtuya overriding files
Restart HA
Add new device from Integrations, and protocol 3.4 shows up
Devices added to HA and turned off and on via Lovelace or calling services via automations

**Comment by wrapper** [comment]
Not sure if this is related but I had the same problem with a climate device, turned out I was just adding the climate entity and not the switch entity.

**Comment by yundin2000** [comment]
same problem here

**Comment by Rotekoppen** [comment]
I have the same problem but find this in my log?
```
NameError: name 'state' is not defined

2022-12-24 00:45:05.840 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):

  File "/config/custom_components/localtuya/common.py", line 317, in _async_refresh

    await self._interface.update_dps()

  File "/config/custom_components/localtuya/tinytuya/tinytuya/__init__.py", line 179, in update_dps

    await self.device.device.updatedps(state, dp_index)

NameError: name 'state' is not defined
```
