### ISSUE TITLE
I can't add the device

### ISSUE THREAD

**Issue by JLOFPV** [willemwouters/localtuya_synced#5]
I can't add the device. Here the error log.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:246
Integration: LocalTuya integration ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 09:02:39 (1 occurrences)
Last logged: 09:02:39

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 591, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 246, in validate_input
    module = import_module('custom_components.localtuya.tinytuya.tinytuya')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.localtuya.tinytuya.tinytuya'

**Comment by prvakt** [comment]
You just need to get this repo [tinytuya](https://github.com/willemwouters/tinytuya.git) and copy tinytuya folder to the /config/custom_components/localtuya/tinytuya/tinytuya (has to be a nested tinytuya in tinytuya folder otherwise the HA logs were shouting "ModuleNotFoundError: No module named 'custom_components.localtuya.tinytuya.tinytuya'").

**Comment by JLOFPV** [comment]
Thank you very much, this has worked for me.
